(define (make-account balance password)
	(define (with-draw amount)
		(if (>= balance amount)
			(begin (set! balance (- balance amount))
					balance)
			"Insufficient fund"))
	(define (deposit amount)
		(set! balance (+ balance amount))
		balance)
	(define (dispatch m p)
		(cond ((not (eq? p password)) (lambda (x) "Incorrect password"))
			  ((eq? m 'withdraw) with-draw)
			  ((eq? m 'deposit) deposit)
			  (else (lambda (x) "Unknown request"))))
	dispatch)
	
(define acc (make-account 100  "123"))
((acc 'withdraw "123") 10)
((acc 'deposit "456") 10)